Hunter 3.05.01
hunter-packages/tesseract pull request #1
Opened 2017-06-13 12:00 UTC by xsacha

2017-06-13 12:10 UTC, ruslo requested changes

2017-06-13 12:10 UTC, ruslo commented on CMakeLists.txt
>  cmake_minimum_required(VERSION 2.8.11)
For Hunter minimum is 3.0:
* https://docs.hunter.sh/en/latest/quick-start/cmake.html

2017-06-13 22:39 UTC, ruslo requested changes

2017-06-13 22:39 UTC, ruslo commented on CMakeLists.txt
>  find_package(OpenCL QUIET)
`find_package(OpenCL REQUIRED CONFIG)`:
* https://github.com/ruslo/hunter/wiki/pkg.opencl

2017-06-15 03:53 UTC, xsacha commented
I think that is everything?

2017-06-15 04:32 UTC, ruslo approved these changes

2017-06-15 04:33 UTC, merged

2017-06-15 04:33 UTC, ruslo commented
https://github.com/hunter-packages/tesseract/releases/tag/v3.05.01-hunter-0